### ISSUE TITLE
Input Field Alignment 

### ISSUE THREAD

**Issue by manikandancode** [SalaniLeo/Immagini#4]
Correct it.

Flake v0.0.4 [Flatpak]
OS : Ubuntu 22.10

![Screenshot from 2023-02-23 18-07-35](https://user-images.githubusercontent.com/46480489/220907877-8040fd5a-94fe-4785-9084-7fd395b6c4cd.png)

**Comment by SalaniLeo** [comment]
Should be fixed now.
