### ISSUE TITLE
Portal call failed

### ISSUE THREAD

**Issue by MadcapJake** [SalaniLeo/Immagini#5]
Hello,

Love what you've got here! I have never really used an appimage before and this looks like a great way to use one in Fedora. 

Running into a problem trying to run [this](https://static.immersed.com/dl/Immersed-x86_64.AppImage) appimage:

```
[jake@fedora ~]$ flatpak run io.github.salaniLeo.flake 
~/Applicationsaaaaaaaasadsadfsad
libEGL warning: wayland-egl: could not open /dev/dri/renderD128 (No such file or directory)
Portal call failed: org.freedesktop.DBus.Error.ServiceUnknown
```

Thank you for your help.

**Comment by SalaniLeo** [comment]
Oh sorry for the ~/Applicationsaaaaaaaasadsadfsad I think I forgot to remove a print test 😂, but for the error I don't know, I have to test it myself because I don't know what may be the cause. I'll look at it when I get home from school

**Comment by SalaniLeo** [comment]
The issue was that in the app .json file "--device=dri" was missing. In a couple of days I'll release the new version with this error fixed.

**Comment by SalaniLeo** [comment]
Also if you encounter any other error please open an issue

**Comment by MadcapJake** [comment]
Thank you! I look forward to the release.
