### ISSUE TITLE
App icon following GNOME's guidelines

### ISSUE THREAD

**Issue by bragefuglseth** [SalaniLeo/Immagini#6]
Immagini utilizes GNOME's platform libraries and design guidelines, but the current app icon (AppImage's logo) looks out of place among other GNOME apps, and creates confusion on whether the app is directly affiliated with AppImage or not. I think the app would benefit from having its own distinct icon with [GNOME's visual style](https://developer.gnome.org/hig/guidelines/app-icons.html).

I can design one if you want me to. I'll start brainstorming, but feel free to stop me if you don't consider it to be necessary :smile:

**Comment by SalaniLeo** [comment]
yea I know, I'm not good at designing icons, so I thought I could use the AppImage's one. I was considering asking someone to design it for me, but you came here at the right moment, so if you want to design it for me it would be really nice.

**Comment by SalaniLeo** [comment]
If you want to talk to me I'm [salaniLeo](https://matrix.to/#/@salanileo:matrix.org) on matrix
